/* fmain.c */
// Xark: NOTE Types altered to match C file (not Manx C promotion rules)
int open_all(void);
int close_all(void)  __attribute__ ((noreturn));
void read_sample(void);
int doorfind(USHORT x, USHORT y, ULONG keytype);
int main(int argc, char **argv);
void xfer(USHORT xtest, USHORT ytest, USHORT flag);
void find_place(short flag);
void load_actors(void);
BOOL set_encounter(USHORT i, USHORT spread);
void checkdead(long i, long dtype);
void load_carrier(short n);
void revive(short is_new);
void screen_size(long x);
void setmood(char now);
void gen_mini(void);
void pagechange(void);
BOOL add_device(void);
void wrap_device(void);
void print_options(void);
void propt(short j, short pena);
void do_option(short hit);
void get_turtle(void);
void gomenu(short mode);
void set_options(void);
void load_all(void);
void load_new_region(void);
void effect(short num, long speed);
void mod1save(void);
