/* fmain2.c */
// Xark: NOTE Types altered to match C file (not Manx C promotion rules)
void dohit(long i, long j, long fc, short wt);
void aftermath(void);
int proxcheck(int x, int y, int i);
int nearest_fig(char constraint, short dist);
int calc_dist(long a, long b);
int move_figure(short fig, short dir, short dist);
void drawcompass(short dir);
void fade_page(short r, short g, short b, short limit, unsigned short *colors);
void colorplay(void);
void ppick(void);
void print(char *str);
void print_cont(char *str);
void extract(char *start);
void announce_container(char *s);
void announce_treasure(char *s);
void name(void);
void map_message(void);
void message_off(void);
void fade_down(void);
void fade_normal(void);
void stillscreen(void);
void shape_read(void);
void read_shapes(long num);
void load_track_range(short f_block, short b_count, APTR buffer, short dr);
void motor_off(void);
void seekn(void);
void prep(short slot);
void load_next(void);
void read_score(void);
void copypage(char *br1, char *br2, short x, short y);
void flipscan(void);
int skipint(void);
unsigned char *into_chip(unsigned char *oldpointer, long size);
void witch_fx(struct fpage *fp);
void do_objects(void);
void leave_item(short i, short object);
void change_object(long id, long flag);
void set_objects(struct object *list, short length, long f);
BOOL copy_protect_junk(void);
int locktest(char *name, long access);
int cpytest(void);
BOOL waitnewdisk(void);
void savegame(short hit);
void saveload(char *buffer, long length);
void move_extent(short e, short x, short y);
void rescue(void);
void win_colors(void);
void day_fade(void);
void do_tactic(long i, long tactic);
void eat(int amt);
void set_loc(void);
